### ISSUE TITLE
Vhosts inaccessibles depuis Chrome et IE - ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by hardware** [hardware/mailserver-autoinstall#4]
La page de setup de postfixadmin et le webmail sont inaccessibles depuis Chrome et IE.
Fait référence au poste : http://mondedie.fr/viewtopic.php?pid=22388#p22388

**Comment by Fi0ra** [comment]
Alors j'ai trouvé comment contourner le problème pour l'instant plus ou moins...
en créant la page 'info.php' afin de tester nginx (j'ai l'habitude d'apache donc j'ai repris à 0), je me suis rendu compte que le serveur nginx allait chercher les pages dans /Var/www/html (et non /var/www), j'ai donc déplacé postfixadmin dans /var/www/html (et j'ai fais un lien dans /var/www afin que le reste du script d'auto install puisse fonctionner)

En passant sans le vhost j'ai réussi à faire mon install de postfix admin, mais le problème reste toujours le même, pour la page du webmail, elle n'est pas non plus accessible par le whost.

Je suis dispo pour te filer les logs qu'il faut, mais plutôt par mail ou en privé

**Comment by hardware** [comment]
Quand tu dis pas accessible, tu as quoi comme type d'erreur ? Une erreur 500 de la part de nginx ?
Il me faudrait les logs (généralement /var/log/nginx/errors.log) lorsque tu tentes d'accéder à postfixadmin ou au webmail, tu peux faire un **tail -f /var/log/nginx/errors.log** en même temps pour voir en live ce qui se produit.

Si tu veux m'envoyer un fichier de log plus complet, utilise cette adresse : contact@meshup.net

**Comment by Fi0ra** [comment]
Quand je fais un tail -f des fichiers logs, que ce soit access ou errors, il ne se passe rien...
dans errors la derniere ligne est à minuit hier, 
unable to write file /var/www/html/postfixadmin/templates_c/wrt556a374db3d5f6_31082592
J'ai résolu ce problème pour continuer l'installation, mais en passant par l'adresse du serveur et pas le sous domaine de postfix.

Quand j'accède au sous domaine, j'ai l'impression qu'il ne sait pas où aller...

sous chrome : 
Page Web inaccessible

ERR_CONNECTION_RESET

sus IE : 
Cette page ne peut pas s’afficher

quand je ping mon sous domaine, je vais bien sur l'ip de mon serveur.

Il n'a pas l'air de prendre en compte le fichier vhost en fait...

**Comment by hardware** [comment]
Que renvoie ces deux commandes sous windows :

```
nslookup postfixadmin.domain.tld
nslookup webmail.domain.tld
```

Bon en fait ton soucis est différent de ce que je pensais, tu as juste un problème de résolution DNS qui peut facilement se résoudre avec le fichier host ou en mettant à jour la zone dns de ton domaine. Mais pourquoi avoir dit 

*La seule solution a été d'installer le package de debian, mais la version est assez ancienne...*

Installer la package de debian ne peut pas être la solution puisque ton soucis est au niveau de la résolution de ton sous domaine.

**Comment by hardware** [comment]
Peu-tu me donner le contenu des 2 vhosts (postfixadmin.conf et rainloop.conf) et le fichier de configuration principal de nginx ?

**Comment by Fi0ra** [comment]
J'ai donc fais un lien
root@lucy:/var/www# ls -la
total 12
drwxr-xr-x  3 root root 4096 May 31 00:54 .
drwxr-xr-x 12 root root 4096 May 31 00:07 ..
drwxr-xr-x  4 root root 4096 May 31 00:54 html
lrwxrwxrwx  1 root root   27 May 31 00:20 postfixadmin -> /var/www/html/postfixadmin/
lrwxrwxrwx  1 root root   23 May 31 00:54 rainloop -> /var/www/html/rainloop/

afin de pouvoir utiliser l'adresse de mon serveur pour faire l'install.
Ci dessous le contenu des 3 fichiers, j'aurais préféré les attacher en pièce jointe, mais ça n'a pas l'air possible :

nginx.conf : 

user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

postfixadmin.conf : 

server {
    listen          80;
    server_name     pfadmin.fiora.fr;
    return 301      https://$server_name$request_uri; # enforce https
}

server {
    listen          443 ssl;
    server_name     pfadmin.fiora.fr;
    root            /var/www/postfixadmin;
    index           index.php;
    charset         utf-8;

    ## SSL settings
    ssl_certificate           /etc/ssl/certs/mailserver_nginx.crt;
    ssl_certificate_key       /etc/ssl/private/mailserver_nginx.key;
    ssl_protocols             TLSv1.2;
    ssl_ciphers               "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;
    ssl_ecdh_curve            secp521r1;

    add_header Strict-Transport-Security max-age=31536000;

    auth_basic "PostfixAdmin - Connexion";
    auth_basic_user_file /etc/nginx/passwd;

    location / {
        try_files $uri $uri/ index.php;
    }

    location ~* \.php$ {
        include       /etc/nginx/fastcgi_params;
        fastcgi_pass  unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

rainloop.conf : 

server {
    listen 	      80;
    server_name   webmail.fiora.fr;
    return 301 	  https://$server_name$request_uri; # enforce https
}

server {
    listen        443 ssl;
    server_name   webmail.fiora.fr;
    root          /var/www/rainloop;
    index         index.php;
    charset       utf-8;

    ## SSL settings
    ssl_certificate           /etc/ssl/certs/mailserver_nginx.crt;
    ssl_certificate_key       /etc/ssl/private/mailserver_nginx.key;
    ssl_protocols             TLSv1.2;
    ssl_ciphers               "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;
    ssl_ecdh_curve            secp521r1;

    add_header Strict-Transport-Security max-age=31536000;

    auth_basic "Webmail - Connexion";
    auth_basic_user_file /etc/nginx/passwd;

    location ^~ /data {
        deny all;
    }

    location / {
        try_files $uri $uri/ index.php;
    }

    location ~* \.php$ {
        include       /etc/nginx/fastcgi_params;
        fastcgi_pass  unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

**Comment by hardware** [comment]
Alors je viens de faire quelques tests :+1: 

Sous Windows :

- Chrome : Ko
- Firefox : Ok
- Opera : Ok

Sous linux :

- Chromium : Ok
- Firefox : Ok
- Opera : OK

Je pense qu'il y a un petit soucis au niveau de handshake SSL, essaye de vider le cache de ton navigateur peut-être. Aussi essaye de changer les paramètres suivants dans les deux vhosts :

```
ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers               "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES256-GCM-SHA256:AES256-GCM-SHA384:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4";
```

**Comment by Fi0ra** [comment]
En effet, après avoir fait le changement des 2 lignes indiquées, cela fonctionne correctement sous chrome.
J'avais testé IE et chrome seulement, après ton commentaire, j'ai testé firefox et ça fonctionnait (avant le changement des 2 lignes).

Merci beaucoup de ton aide, je vais pouvoir passer à la suite, j'ai l'impression que mon imap ne fonctionne pas (outlook me le refuse), mais je fouille, puis il faut aussi que je mette mon certificat ssl plutôt qu'un autosigné :D Et que je finisse j'ajouter proprement les domaines webmail etc...)

Merci encore :D

**Comment by hardware** [comment]
Sauf qu'il faut impérativement que tu supprimes les liens symboliques et même le vhost par défaut (/var/www/html et /etc/nginx/sites-enabled/default...) parce que tout le monde peut accéder à ta configuration postfix : http://94.23.233.186/postfixadmin/setup.php

**Comment by Fi0ra** [comment]
C'est fait, merci.
