### ISSUE TITLE
postfix download URL error

### ISSUE THREAD

**Issue by gishy** [hardware/mailserver-autoinstall#5]
l'url sourceforge de pose problème, à la place de :
http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-2.92/postfixadmin-2.92.tar.gz
c'est http://freefr.dl.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-2.92/postfixadmin-2.92.tar.gz
le début change : downloads.sourceforge.net => freefr.dl.sourceforge.net

**Comment by hardware** [comment]
Merci pour ce retour ;)
